# Generated by Django 4.2.1 on 2023-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('ciudad', models.CharField(max_length=255, null=True, verbose_name='Ciudad')),
                ('nombre_calle', models.CharField(max_length=255, verbose_name='Nombre de la Calle')),
                ('telefono', models.IntegerField(verbose_name='Número de teléfono')),
                ('fecha_de_alta', models.DateField(verbose_name='Fecha de Alta')),
                ('estado', models.BooleanField(verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'Cliente',
                'ordering': ['id'],
            },
        ),
    ]
