# Generated by Django 4.2.1 on 2023-05-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretipo', models.CharField(max_length=255, verbose_name='Tipo de Mascota')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'db_table': 'TipoMascota',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=255, verbose_name='Propietario')),
                ('numero_chip', models.IntegerField(blank=True, verbose_name='Número de chip')),
                ('nombre_mascota', models.CharField(max_length=255, verbose_name='Nombre de la Mascota')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estado', models.BooleanField(verbose_name='Estado')),
                ('tipo_mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.tipomascota', verbose_name='Tipo de Mascota')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'db_table': 'Mascota',
                'ordering': ['id'],
            },
        ),
    ]
