# Generated by Django 4.2.1 on 2023-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0004_historiaclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_calle',
            field=models.IntegerField(null=True, verbose_name='Número de la calle'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(max_length=100, null=True, verbose_name='Color de la Mascota'),
        ),
    ]
